# permissions to do edit himessages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: himessage-editor-role
rules:
- apiGroups:
  - messaging.abyster.com
  resources:
  - himessages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messaging.abyster.com
  resources:
  - himessages/status
  verbs:
  - get
  - patch
  - update
