# permissions to do viewer himessages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: himessage-viewer-role
rules:
- apiGroups:
  - messaging.abyster.com
  resources:
  - himessages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - messaging.abyster.com
  resources:
  - himessages/status
  verbs:
  - get
